CREATE TABLE [dbo].[STUDENT_INFO]
(
	[STUDENT_ID] INT NOT NULL PRIMARY KEY, 
    [FNAME] NVARCHAR(50) NULL, 
    [LNAME] NVARCHAR(50) NULL, 
    [EMAIL] NVARCHAR(50) NULL, 
    [PASSWORD] NVARCHAR(50) NULL
)
