CREATE TABLE [dbo].[PROFESSOR_INFO]
(
	[PROFESSOR_ID] INT NOT NULL PRIMARY KEY, 
    [PROFESSOR_FNAME] NVARCHAR(50) NULL, 
    [PROFESSOR_LNAME] NVARCHAR(50) NULL, 
    [STATUS] NVARCHAR(50) NULL, 
    [HIRE_DATE] NVARCHAR(20) NULL
)
